source 'https://rubygems.org'

ruby '2.7.2'

gem 'bcrypt'
gem 'dry-auto_inject'
gem 'dry-monads'
gem 'dry-system'
gem 'dry-validation'
gem 'jwt'
gem 'rom'
gem 'rom-sql'
gem 'pg'

gem 'dotenv'
gem 'rake'

gem "hanami-controller"
gem "hanami-router"

group :test, :development do
  gem 'pry'
end

group :test do
  gem "rack-test"
  gem 'rspec'
  gem 'database_cleaner-sequel'
end
