source 'https://rubygems.org'

gem 'dry-initializer'
gem 'fast_jsonapi'
# gem 'jsonapi-serializer', git: 'git://github.com/jsonapi-serializer/jsonapi-serializer'
gem 'sinatra', '~> 2.0'
gem 'sinatra-contrib', '~> 2.0', require: false
gem 'puma', '~> 4.3'
gem 'sequel', '>= 5'
gem 'sequel_pg', '>= 1.12', require: 'sequel'
gem 'tux'
